### PR TITLE
add build arg statements to the Dockerfile

### PR DESCRIPTION
**Pull request by hardyoyo**
so that the documented method of specifying a CANTALOUPE_VERSION is correct

### CODE REVIEW

**Comment by hardyoyo** [comment]
In case it helps clarify anything, I followed this [very helpful guide](https://vsupalov.com/docker-arg-env-variable-guide/) as well as the official [Dockerfile reference](https://docs.docker.com/engine/reference/builder/#arg).

**Comment by gravesm** [comment]
Thanks for the PR. Would you mind making two changes before we merge?

1. The CANTALOUPE_VERSION ARG is specified twice. Remove the instance without the default value.
2. Move both the CANTALOUPE_VERSION ARG and ENV to right before cantaloupe is downloaded. This will avoid invalidating the build cache all the way up to there when switching versions.

**Comment by hardyoyo** [comment]
1. I think this is possible, I copied this work from our fork which uses a multi-stage build and needed the ARG to exist outside of the image, however, for this simpler single-stage build, moving the ARG inside the image should work.
2. I left the ENV where I found it, but I can easily move it if you prefer.

**Comment by gravesm** [comment]
Thanks!

**Pull request merged**
